---
deployment:
  tasks:
    - export DEPLOYPATH=/home/danir1159311/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp programa-ascensao.html $DEPLOYPATH
    - /bin/cp bgdani.webp $DEPLOYPATH
